# Generated by Django 4.2.1 on 2023-06-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Python", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Hello", max_length=255)),
                ("duration", models.CharField(default="2hrs", max_length=50)),
                (
                    "skills_req",
                    models.CharField(default="Python Basics", max_length=255),
                ),
                ("credits", models.IntegerField(default=0)),
                ("pdf", models.FileField(default="No pdf", upload_to="pdfs/")),
                ("image", models.ImageField(default="No image", upload_to="images/")),
                ("points", models.ManyToManyField(default=list, to="daksha.point")),
            ],
        ),
    ]
