# Generated by Django 4.2.1 on 2023-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="points",
        ),
        migrations.AddField(
            model_name="project",
            name="points",
            field=models.ManyToManyField(default=list, to="daksha.point"),
        ),
    ]
