# Generated by Django 4.2.1 on 2023-06-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0002_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="files",
            field=models.FileField(
                upload_to="submissions/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>"
            ),
        ),
    ]
