# Generated by Django 4.2.1 on 2023-06-29 20:01

import daksha.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daksha", "0003_alter_submission_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="submission",
            name="files",
            field=models.FileField(upload_to=daksha.models.user_submission_path),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
