# Generated by Django 4.2.1 on 2023-07-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0004_project_content_alter_submission_files_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(default="Programming", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
