# Generated by Django 4.2.1 on 2023-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0005_project_category_project_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(default="Logo", upload_to="images/"),
        ),
    ]
