# Generated by Django 4.2.1 on 2023-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0006_project_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="about_company",
            field=models.TextField(default=""),
        ),
    ]
