# Generated by Django 4.2.1 on 2023-07-05 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0007_profile_rank_project_about_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="projects_done",
            field=models.ManyToManyField(default=list, to="daksha.project"),
        ),
        migrations.AddField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
