# Generated by Django 4.2.1 on 2023-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0008_profile_accuracy_profile_projects_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tool",
            field=models.IntegerField(default=0),
        ),
    ]
