# Generated by Django 4.2.1 on 2023-07-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0009_project_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="level",
            field=models.FloatField(default=0.0),
        ),
    ]
