# Generated by Django 4.2.1 on 2023-07-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0011_alter_project_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="duration",
            field=models.IntegerField(default=2),
        ),
    ]
