# Generated by Django 4.2.1 on 2023-07-05 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daksha", "0012_alter_project_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="accuracy",
        ),
        migrations.CreateModel(
            name="credits_given",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits_delivered", models.IntegerField(default=0)),
                (
                    "projects_done",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="daksha.project"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
