# Generated by Django 4.2.1 on 2023-07-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daksha", "0013_remove_profile_accuracy_credits_given"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="got_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="credits_given",
        ),
    ]
